KayStrobach:
  Ldap:
    host: ''
    port: ''
    admin:
      dn: ''
      password: ''
    defaults:
      attributes: 'dn,uid,givenName,sn,uidNumber,employeeType,mail,ou,userPassword,employeeNumber'